# Generated by Django 3.1.7 on 2021-09-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('bio1', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile')),
                ('behance_profile_url', models.CharField(blank=True, max_length=120, null=True)),
                ('twitter_profile_url', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_profile_url', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_profile_url', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_profile_url', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('asset_name', models.CharField(max_length=120)),
                ('asset_title_tag', models.CharField(max_length=255)),
                ('asset_description', models.CharField(max_length=300)),
                ('asset_slug', models.SlugField(null=True)),
                ('asset_price', models.IntegerField()),
                ('category', models.CharField(default='coding', max_length=255)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSeaAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=300)),
                ('asset_name', models.CharField(max_length=120)),
                ('asset_slug', models.SlugField(null=True)),
                ('asset_token_id', models.CharField(max_length=300)),
                ('likes', models.ManyToManyField(related_name='opensea_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
