# Generated by Django 3.1.7 on 2021-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openseaasset',
            name='asset_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='openseaasset',
            name='asset_token_id',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='openseaasset',
            name='contract_address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
